# This is a basic workflow to help you get started with Actions

name: whis-dev Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am IST
    - cron: '0 15 * * *'

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@V1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
